- grammarinator/generate.py
Add seed as command line argument to make generating repeatable (it is need to be applied combined with "-j 1" argument, because it needs to run as a single process), if seed is not given by the user, the generating is still random for every generating.
Signed-off-by: matedabis mdabis@inf.u-szeged.hu
> Add seed as command line argument

- grammarinator/process.py
- tests/grammars/Charset.g4
I was generating a fuzzer for the JSON grammar from `antlr/grammars-v4` and noticed some differences between how ANTLR and grammarinator handle charsets.
The specific cases I noticed:
`["\\\u0000-\u001F]` represents the characters `"` and `\` and the range `\u0000-\u001F`. However, `re.split(r'(\w-\w)', src)` doesn't split as intended so grammarinator parses this as five characters.
`[+\-]` represents two characters (`+` and `-`) in ANTLR, with `-` being escaped. However, this escape isn't handled by `.decode('unicode_escape')`, so grammarinator parses it as `+`, `\`, and `-`.
I ported a simplified version of ANTLR's charset parsing code to Python to replace the current handling. It handles the above cases correctly, as well as adds the ability to specify unicode using the `\u{123}` …
> Improved charset handling

- grammarinator/process.py
- grammarinator/runtime/tree.py
- Re-raising exceptions using the `from` keyword.
- Using Python 3 style `super()` without arguments.
> Fix lint issues

- grammarinator/generate.py
Repeating test generation after a failure could cause infinite recursion earlier. This is disabled hereafter.
> Disable test regeneration in case of failure

- grammarinator/runtime/cooldown_model.py
The identifier of cooldown weights didn't contained the identifier of the alternation only the containing rule name and the chosen alternative index which doesn't informative enough to identify the target point.
> Fix weight calculation of CooldownModel

- grammarinator/process.py
Before this commit, empty alternatives were handled during the processing of their children, which caused the generation of harmless but superfluous "pass" statements/lambda nodes. Now, we examine the amount of children when the processing of the alternative has finished and add lambda/ pass only if it's needed.
> Simplify the handling of empty alternatives

- grammarinator/runtime/cooldown_model.py
Due to the downscaling at cooldown model, some weigths might be too small, which can be avoided by normalization.
> Normalize cooldown weights to sum up to 1

- .github/workflows/main.yml
- README.rst
- grammarinator/generate.py
- grammarinator/parse.py
- grammarinator/parser_builder.py
- grammarinator/process.py
- grammarinator/runtime/default_model.py
- grammarinator/runtime/tree.py
- setup.cfg
- tests/parse.py
- tests/run_grammars.py
Python3.5 has reached the end of its lifetime two years ago, hence Grammarinator also stops supporting it. The patch introduces several Python3.6 features like the usage of f-strings or random.choices() and it updates the docs and tests.
> Drop support of Python3.5

- .pylintrc
Grammarinator uses f-strings since #63 hence executing the linter checker above is reasonable.
> Re-enable the 'consider-using-f-string' pylint checker

- grammarinator/process.py
Extend the current duplicate rule handling with disabling the duplication of lexer rules inside lexer modes. This is disabled in ANTLR, too.
> Fix duplicate rule handling

- grammarinator/process.py
Since the ANTLR grammars are converted to recognizer in built time, the OUTDIR/antlr directory is not created anymore by grammarinator-process, hence trying to remove this directory is incorrect (even if it didn't cause any failure since errors were disabled in rmtree).
> Remove the superfluous --disable-cleanup argument from grammarinator-process

- grammarinator/runtime/tree.py
The improved printing implementation displays the content of tokens, too. Although lexer rules can refer further lexer or fragment rules, for readability, only the toplevel lexer rules are printed with its childrens content concatenated.
> Improve the printing of the generated tree

- MANIFEST.in
- pyproject.toml
- setup.cfg
- tox.ini
This helps running tox when working with a development mode install, but requires adding a manifest template.
> ANTLeRinator 1!3.0.0 doesn't clean generated files before sdist

- grammarinator/generate.py
Inline tokens are named as `<INVALID>` by ANTLR. When such a node was chosen to be mutated then Grammarinator tried to regenerate them according to a rule definition called `<INVALID>` which did not exist, of course. The patch disables the mutation of such nodes since inline tokens are constants, hence mutating them would not have any importance either.
Fixes #80.
> Fix the mutation of inline tokens

- grammarinator/generate.py
- grammarinator/runtime/cooldown_model.py
Before this commit, weights were initialized at every test cases when generating them in parallel. From now on, weights will be properly shared and locked if needed.
> Enable cooldown and other models to retain weights across test cases

- grammarinator/generate.py
- grammarinator/process.py
- grammarinator/resources/codegen/GeneratorTemplate.py.jinja
This new funcionality helps identifying cycles in the graph and it looks for unavailable rules from a user-defined start rule. Furthermore, it finds the farthest rule from a starting rule
- this can be predefined or the first parser rule. This information can be useful by generation when parametrizing the max-depth argument. The node classes representing the grammar tree are extended with __str__ and print_tree methods.
> Add grammar analyzer functionality to grammarinator-process

- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
Only rules, quantifiers, and alternations store information about min depth, so make that explicit in the internal representation by removing the `min_depth` field from the root of the graph node class hierarchy. Moreover, differentiate between graph nodes that contain a single min depth (rules and quantifiers, add `min_depth` field) and those that contain multiple min depths (alternations, add `min_depths` field).
> Improve the internal representation and calculation of min depths

- grammarinator/generate.py
- grammarinator/tool/__init__.py
- grammarinator/tool/generator.py
Instead of requiring several hard-coded parameters to guide the instantiation of the generator with a specific set of models and a given set of listeners, all that logic is encapsulated into a so-called generator factory.
A generator factory is a generalization of a generator class: it has to instantiate a generator object. But it has to set the decision model and the listeners of the generator as well. (In the simplest case, it can be a generator class, but in more complex scenarios - like the `grammarinator-generate` script - some wrapper is needed.)
This generalization helps to greatly simplify the API of the `GeneratorTool` and also simplifies its internal implementation.
Also moved the responsibility of reproducibility from the tool to the script.
Also removed the support for string …
> Simplify GeneratorTool by removing the complexity of generator instantiation

- grammarinator/cli.py
- grammarinator/generate.py
- grammarinator/parse.py
- grammarinator/process.py
- grammarinator/tool/generator.py
- grammarinator/tool/parser.py
- grammarinator/tool/processor.py
- tests/grammars/SurrogatePairs.g4
The support for encoding error handling has been motivated by errors caused if Unicode surrogate pairs are in the generated tests, which cannot be written to output with utf-8 codec.
Also added a unit test to create a test case with character outside the basic multilingual plane of Unicode, both in six-position-hex format and with surrogate pair.
> Add support for encoding error handling

- grammarinator/tool/processor.py
- tests/grammars/DotOption.g4
Options given on the CLI were added too late to the internal representation of the grammar, when the option specified in the grammar file was already taken into account. So, `-Ddot=...` could not override `options { dot=...; }`.
> Fix CLI override of the dot grammar option

- examples/grammars/HTMLParser.g4
- tests/grammars/Arguments.g4
- tests/grammars/Charset.g4
- tests/grammars/Curly.g4
- tests/grammars/CustomWeightsModel.g4
- tests/grammars/DefaultRule.g4
- tests/grammars/DispatchingModel.g4
- tests/grammars/EmptyAlternatives.g4
- tests/grammars/Eof.g4
- tests/grammars/Hello.g4
- tests/grammars/ImagToken.g4
- tests/grammars/Importer.g4
- tests/grammars/LifeCycle.g4
- tests/grammars/Listeners.g4
- tests/grammars/Locals.g4
- tests/grammars/MinDepth.g4
- tests/grammars/NoAction.g4
- tests/grammars/Returns.g4
- tests/grammars/SeparateParser.g4
- tests/grammars/SimpleAlternations.g4
- tests/grammars/Whitespace.g4
The default value for `-j` (number oj jobs) in `grammarinator-generate` is based on the number of CPUs available on the system. This is good (adaptive) in practice but not so good for testing (when reproducibility is preferrable).
Therefore, `-j` is explicitly specified in all unit tests. All unit tests try single-process test case generation (using `-j 1`) and those test cases where multi-process behaviour needs to be tested, do so (using `-j 2`).
> Better control of multiprocessing in unit tests

- grammarinator/tool/processor.py
The difference between the `name` and `id` properties of a rule is that the `id` contains the value of a label if exists, too, which results in a more accurate identifier for a rule. Hence, using the `id` property instead of `name` for identifying the container rule of an alternation, quantifier or a charset is reasonable. Similarly, using it in the `__str__` method of a rule is more beneficial.
> Fix the usage of rule.name and rule.id

- docs/guide/grammar_overview.rst
- grammarinator/tool/processor.py
- tests/grammars/Dot.g4
Until now, the `dot` wildcard was handled the same way both in lexer and parser rules: it meant the generation of a single character. But it was wrong. From now, if `dot` is placed in a parser rule, it triggers the generation of a random token, as expected by ANTLR. The only limitation is that lexer modes are not taken into account (for now), since it would cause remarkable complication.
> Improve the handling of the `dot` wildcard in parser rules

- grammarinator/runtime/serializer.py
This should be easier on the memory.
(Also fix the docstring.)
> Rewrite simple_space_serializer to use a generator instead of a list

- .readthedocs.yml
Both build.os and build.tools became mandatory. The builds on RTD will stop working without them after Oct 16, 2023.
> Migrating to build.os on ReadTheDocs

- .readthedocs.yml
Use string values as per readthedocs/readthedocs.org#10800
> Fix build.tools.python in ReadTheDocs config

- grammarinator/tool/processor.py
- tests/grammars/Charset.g4
If the set to be inverted contained consecutive characters, then multirange_diff inserted empty ranges into the charset, which threw error. The patch fixes this.
> Fix not-set range calculation

- .github/workflows/main.yml
All GH Action runner images have Java pre-installed. Both ubuntu-latest and macos-latest have Java 11+ as default. Only windows-latest has Java 8 as default. So avoid a superfluous setup-java step in all jobs except the tests on windows-latest.
> Avoid setup-java step on GH Actions if possible

- grammarinator/generate.py
- grammarinator/tool/generator.py
In this mode everything is executed as in a normal use case, except that nothing is saved to disk or printed to stdout.
> Enable dry-run mode for grammarinator-generate

- grammarinator/tool/default_population.py
- grammarinator/tool/processor.py
- tox.ini
Disabling W503 which complained about line breaks before binary operators.
> Enable splitting long conditions into multiple lines

- .pylintrc
- grammarinator/runtime/generator.py
- grammarinator/runtime/listener.py
- grammarinator/runtime/model.py
- grammarinator/runtime/population.py
- grammarinator/runtime/rule.py
- grammarinator/tool/default_population.py
- grammarinator/tool/generator.py
- grammarinator/tool/parser.py
- grammarinator/tool/processor.py
In Python3, object is the implicit superclass. There is no need to explicitly define it.
> Remove the explicit `object` superclass definition from classes

- grammarinator/runtime/cooldown_model.py
- grammarinator/runtime/default_model.py
- grammarinator/runtime/dispatching_model.py
- grammarinator/runtime/generator.py
- grammarinator/runtime/model.py
- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/DispatchingModel.g4
Both the tools (the processor, the codegen template) and the runtime (the models) contain code that deals with quantifiers. Quantification has lower and upper bounds, which are traditionally named min and max. However, having min and max as function arguments (like in models) shadows the Python builtins. To avoid this and make the builtins available, min is renamed to start while max is renamed to stop all around the code base (terminology borrowed from the range Python builtin).
> Don't shadow builtin min and max in quantifier-related code

- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/Locals.g4
- tests/grammars/Returns.g4
Even if locals or returns are not initialized in the grammar, the generated code must initialize them to None at least to be syntactically correct.
> Fix code generation for uninitialized locals and returns

- grammarinator/tool/default_population.py
By fixing the ordering of nodes in annotate and node filtering, seeded test generation became deterministic in case of mutation and recombination, too.
Fixes #170.
> Ensure the reproducibilty of the mutation and recombination operators

- grammarinator/tool/default_population.py
Related changed
- Drop support of deepcopy on trees since they are never copied
- Update documentation of tree save
> Annotate default population's tree when initialized

- examples/fuzzer/HTMLCustomGenerator.py
- grammarinator/runtime/generator.py
- grammarinator/runtime/rule.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/CustomSubclassGenerator.py
- tests/grammars/ImagToken.g4
- tests/grammars/SuperGenerator.py
Callers, typically Contexts, can take this responsibility. This also ensures that by the time a child is added to its parent, the child object is already fully constructed.
Related minor fixes:
- Make UnparserRule init argument keyword-only to align it with Rule and UnlexerRule.
- Don't pass parameters by name when using RuleContexts in tests to align the usage with generated code.
> Do not add rule nodes to their parent during initialization

- .pylintrc
- docs/grammarinator.runtime.rst
- grammarinator/runtime/rule.py
- grammarinator/tool/default_population.py
In addition to the classic "informal" (str) and "official" (repr) formats, a "debug" format is supported as well. Plus, the formatting logic is now in the related classes.
> Implement string formatting for tree nodes

- grammarinator/cli.py
- grammarinator/generate.py
- grammarinator/parse.py
- grammarinator/tool/__init__.py
- grammarinator/tool/default_population.py
- grammarinator/tool/tree_codec.py
- tests/grammars/LifeCycle.g4
The now-added tree codec framework provides means to convert between trees and arrays of bytes. Moreover, enhanced codecs can also support the serialization and deserialization of additional data (called annotations). The default population implementation is updated to make use of the tree codec framework and make optimal use of the annotations if supported by the chosen codec.
At the moment, two tree codecs are supported: a json-based, with no support for annotations, and a pickle-based, with support for annotations.
Note: The internal format of the files read and written by the pickle-based tree codec are NOT backward compatible with the serialized trees created with previous versions.
> Add support for multiple tree file formats

- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/ArgumentsInAlternations.g4
- tests/grammars/Locals.g4
- tests/grammars/Returns.g4
Both prefix or postfix type notation are supported in addition to the already existing no-type notation. At the moment, types are only used (and meaningful) for args, where they become type hints in the generated python code.
> Support types in rule attribute definitions (args, locals, returns)

- grammarinator/generate.py
- grammarinator/tool/default_population.py
- No need to exit in grammarinator-generate if population directory does not exists yet, since DefaultPopulation creates it if needed.
- Make better use of the internal data structure nodes_by_name.
> DefaultPopulation-related improvements

- grammarinator/tool/parser.py
- tests/grammars/LabeledAlternatives.g4
In ANTLR, there is no such restriction on the name of a labeled alternative that it cannot start with the name of its container rule. The only restriction is that it cannot match completly with any rule name. The patch removes such a mistaken restriction from the Grammarinator parse implementation.
> Enable labeled alternatives to start their name with their rule name

- grammarinator/runtime/rule.py
- grammarinator/tool/tree_codec.py
- `Rule.left_sibling` and `Rule.right_sibling` had misleading documentation stating that "no parent" or "inconsistent state" raised `ValueError`. However, "no parent" raised a different kind of error, while "inconsistent state" was explicitly hidden by the implementation. Fixed "no parent" not to raise, but "inconsistent state" to do raise and error.
- `Rule.replace`, `UnparserRule.insert_child`, and `UnparserRule.add_child` did not ensure that the node to be added to the tree was removed from its parent (if it had any). Fixed to remove the added node from its original parent.
- `Rule.delete` got renamed to `Rule.remove` to better describe its functionality (the node is not deleted, only removed from its parent).
- `UnparserRule.last_child` property setter was removed, since …
> Rule API revision

- grammarinator/tool/processor.py
Alternation condition values can be stored as a list or as an identifier referring to an entry of the graphs appropriate container. However, the __str__ method of AlternationNode handled this incorrectly. This is fixed now.
> Fix tree printing of alternations in the processor

- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/LifeCycle.g4
The new approach produces postfixed methods from alternatives with recurring names. These methods create rule nodes without postfixes just like before. To make possible to regenerate these rules during mutation, a further generator method was added without postfix - to match the name of the created rules. It groups together all the alternatives with common labels and makes possible to regenerate the nodes of the common labels.
> Support rule labels with recurring names

- MANIFEST.in
- setup.cfg
- When tool API got split from CLI, MANTIFEST.in was not updated to exclude the right files.
- When test folder got changed into a package, setup.cfg was not updated to exclude the new package from the distribution.
Fixes #209
> Fix leftover path problems

- grammarinator/tool/parser.py
If a combined grammar doesn't contain any lexer rule definitions but inline literal constants only, then the symbolicName list of the parser is empty. The patch prepares the parser of Grammarinator for such cases.
> Fix the indexing of symbolic names of lexer rules in parser

- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
Joining the parts of node identifiers is unnecessary and loses information by concealing the boundaries of rule names, label names, and label indices. The patch employs tuples instead of concatenated strings.
> Use tuple IDs for graph nodes in processor

- docs/guide/population.rst
- grammarinator/cli.py
- grammarinator/parse.py
Until now, grammarinator-parse expected to receive a list of files as inputs to be processed. From now on, it also accepts directories, which will be recursively traversed. Furthermore, file patterns are also supported to easily filter and parse tests by patterns.
> Extend the input formats recognized by grammarinator-parse

- grammarinator/tool/processor.py
Fix the ID of the default rule in tree_print and improve the error message if it's not used properly.
> Improve tree printing in processor

- grammarinator/tool/tree_codec.py
From now, not only the flatbuffers but also the json tree codec represents the infinite quantification limit with the value of -1.
> Unify the handling of infinite quantification limit across tree codecs

- grammarinator/tool/processor.py
The change is needed since even if ANTLR enables to have lower-case label names, but it will convert them to start with capital letter eventually, since the Context class created from them must be capital. Since the name of this Context class will be used by grammarinator-parse to create nodes from labelled rules, we need to ensure a common naming schema.
> Ensure that label names in processor start with capital letter

- grammarinator/runtime/generator.py
- tests/grammars/Fragment.g4
Since token sub-rules (e.g., fragments) are not represented by unique nodes in the tree, even though listeners are called when the generation of a sub-rule starts or ends, the listeners only see the top-level token node and the name of the top-level lexer rule.
This commit changes this by faking the top-level token node to have the name of the sub-rule rule while generating the sub-rule.
> Ensure that listener sees correct name when lexer rule refers to another lexer rule

- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/InitAfter.g4
Previously, only the first line got indented in the generated code, making it hard to write multi-line actions.
> Properly indent multi-line init and after actions

- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/RecurringLabelTrampolines.g4
These trampoline functions are normally only used in mutation scenarios when a subtree of a labeled alternative is re-generated by calling the function named as the labeled alternative. If the label is recurring, this function is an artificial trampoline that calls one of the functions that have the same name prefix but differ in a numbered suffix (e.g., `rule_Label` calls `rule_Label_1` or `rule_Label_2`). The trampoline function is expected to be transparent, i.e., to create a tree structure as if one of the number-suffixed functions was called.
However, until now, the tree structures created by the trampolines and the way the trees were created were incorrect. The trampoline created two extra nodes in the tree: one UnparserRule node named as the labeled alternative (e.g., `rule_Lable`) …
> Fix the trampoline functions of recurring labeled alternatives

- grammarinator/tool/generator.py
Immutable rules were filtered out in the previous version as well, but it was repeatedly performed in the mutators. This is moved into Annotations now, which simplifies the code.
> Filter immutable rules out from annotations

- .github/workflows/main.yml
A race condition in multiprocessing.Pool started causing problems on GH Actions. The issue never appears when testing locally. Disabling Py3.10/Ubuntu tests because they cause most of the failures.
> Disable testing Py3.10 on Ubuntu on GH Actions

- grammarinator/generate.py
- grammarinator/tool/generator.py
Besides, creator selection was moved into a separate method to enable customizing it in a subclass. Furthermore, since input selection was moved before mutation selection, hence the mutators are now expecting receiving input individuals as parameter.
> Swap the order of mutator and input selection

- .github/workflows/main.yml
With cooldown factor retired and shared weight dictionaries gone, the errors are (should be) gone as well.
> Re-enable testing Py3.10 on Ubuntu on GH Actions

- grammarinator/generate.py
The help string of `-n` has been mentioning `inf` as a valid value and the code has been prepared for continuous generation for years, but the argument parser never accepted anything but integers.
> Enable `-n inf` on the CLI of grammarinator-generate

- grammarinator/pkgdata.py
It has already been dropped from setup.cfg.
> Don't import importlib_metadata since Py3.8 already has it as importlib.metadata

- grammarinator/runtime/serializer.py
The new `tokens()` method of rule nodes makes it easier to access their leaf node sequences. This update leverages the `tokens()` method to simplify the implementation of `simple_space_serializer`.
> Simplify simple_space_serializer using `tokens()` method

- grammarinator/tool/generator.py
The mutator is improved by ensuring to replicate non-empty subtrees only and instead of inserting a single copy, a random number of replicant will be added that still obeys the quantifier restrictions.
> Improve the `replicate_quantified`

- grammarinator/tool/generator.py
It is more efficient to do this only once, not at every call to create() or mutate().
> Add unrestricted mutators to the list of available options in `GeneratorTool.__init__()`

- grammarinator/runtime/rule.py
- Vertically compact the repr format of ParentRules with children
- Avoid empty lines in the dbg format of ParentRules with no children
- Don't show None as the name in the repr format of UnparserRuleQuantifieds
- Implement reusable computations of repr and dbg formats of children of ParentRules
- Use f-strings instead of .format() where possible
> Improve the formating of (Parent)Rules

- grammarinator/tool/generator.py
If token limit is inf, an infinite (or rather, NaN) number of copies could be made of a */+-quantified subtree.
> Fix GeneratorTool.replicate_quantified when token limit is inf

- grammarinator/parse.py
- grammarinator/tool/parser.py
This allows to return to the old, strict behaviour of parsing when needed, but use the new, more permissive parsing as default.
> Add `--strict` option to discard tests that parse with syntax error

- docs/guide/models.rst
- grammarinator/runtime/model.py
- The example grammar was incorrect, at least for parsing. For ANTLR, character classes are invalid in parser rules, may only be used in lexer rules. Thus, grammar was rewritten to use lexer rules.
- In the python examples, indentation was off by one for `quantify` and `charset` methods. Fixed.
- The `quantify` methods in the examples used an old API: the number and names of arguments was incorrect, and the methods still acted as generators. So, the `cnt` argument was added, `min` and `max` were renamed to `start` and `stop`, and `return` was used instead of `yield`ing.
- Since the `decimal` rule in the grammar got turned into an lexer rule, `Decimal` nodes don't have children anymore. Thus, `charset` methods in the examples have been updated to make decisions based on token length …
> Fix user guide about models

- grammarinator/tool/parser.py
Ensure correct matching between grammar tree nodes and grammar graph lexer nodes by enforcing the following conditions:
* The grammar graph node must be an UnlexerRuleNode, and the tree node must be an UnlexerRule.
* Their names must match, or if the tree node is named ('<INVALID>',), the graph node’s name must start with T__, indicating a constant literal.
* In the latter case, the content of the literals must also be compared by checking the src field of the tree node against the src field of the single LiteralNode neighbor in the grammar graph.
This patch ensures that this comparison is correctly applied.
> Fix literal matching in parser

- grammarinator-cxx/libgrammarinator/include/grammarinator/tool/GeneratorTool.hpp
- grammarinator-cxx/tools/generate.cpp
- grammarinator/generate.py
- grammarinator/tool/generator.py
This patch introduces memoization support for both the Python and C++ backends, ensuring that each blackbox generator produces at least the user-specified number of unique test cases - provided that they can be generated within the configured maximum number of attempts per test case.
Co-authored by: Renáta Hodován <reni@inf.u-szeged.hu>
> Add memoization of generated test cases to ensure uniqueness

- grammarinator-cxx/tools/CMakeLists.txt
When building the C++ version, the binary executable tool that generates test cases was named `generate-SUFFIX` (where `SUFFIX` stands for the grammar/format used). To make the naming more aligned with the Python version and to make the tool's relation to Grammarinator clearer, the name of the tool is prefixed with `grammarinator-`.
Also added directives on how to install the tool if the project is installed.
> Add the grammarinator- prefix to the name of the generate-* binary

- .github/workflows/main.yml
- README.rst
- setup.cfg
Python 3.8 reached its end of life in October 2024, hence we do not support it either.
> Remove support of Python 3.8

- grammarinator-cxx/libgrammarinator/include/grammarinator/runtime/Serializer.hpp
* Removed unused comments and include.
* Remove unnecessary EOF check from SimpleSpaceSerializer.
> Cleanup seralizer implementation in C++

- grammarinator-cxx/libgrammarinator/CMakeLists.txt
Requiring xxhash seems to fail on Linux, while it works on MacOS and Windows. May be caused by case-sensitive/insensitive file system differences.
> Require package xxHash in CMakeLists

- grammarinator-cxx/libgrammarinator/include/grammarinator/tool/DefaultPopulation.hpp
- grammarinator-cxx/tools/generate.cpp
- Use `std::filesystem`-based techniques to collect files in a directory instead of `glob.h`, which is POSIX-only.
- Avoid implicit conversions between `std::filesystem::path` and `std::string`.
This helps a lot on non-POSIX systems like Windows/MSVC.
> Improve standard-conformance of the C++ code base
