renatahodovan/grammarinator

- grammarinator/generate.py
My use case for grammarinator involves setting up a CI environment that continuously receives fuzzed queries. To this end, this PR introduces support for the flags `-o stdout` and `--infinite`.
These flags are not expected to work in parallelized environments, but I think this is a useful alternative to tests written to disk. Let me know if this idea is interesting to you and, if so, what this PR needs!
> Add stdout and infinite targets

- grammarinator/generate.py
Currently, grammarinator forces the output to many unique files or to stdout. I want to be able to have the outputs be written to just a single file so I can perform continuous fuzzing of an application.
e.g. This is my use case
```
fuzzer = generate.Generator('fuzzer/JSONUnlexer.py', 'fuzzer/JSONUnparser.py', 'json', 'tests/test.json',
max_depth=50)
while True:
fuzzer.create_new_test()
```
I would just like 1 file to be created and I will create others as needed. The multiple file generation functionality is retained.
> Add support for writing to a single file

- grammarinator/runtime/cooldown_model.py
- grammarinator/runtime/default_model.py
- grammarinator/runtime/dispatching_model.py
This is to synchronize terminology both within project and with `random.choices`.
> Rename argument of `Model.choice` from `choices` to `weights`

- grammarinator/process.py
Rule redefinitions could be the root of unexpected behaviours (like the previous handling when multiple definitions were concatenated). ANTLR also disables explicit redefinitions (even if it can be by-passed by importing the duplications due to a bug: https://github.com/antlr/antlr4/issues/1202).
> Raise error in case of rule redefinition

- grammarinator/runtime/tree.py
When loading a tree with pickle, then infinite recursion could happen in __getattr__ (see comment for details).
Besides, it fixes the name of the node missing the requested attribute.
> Fix infinite recursion issue when loading trees with pickle

- grammarinator/generate.py
`create_new_test` in Generator contained a too broad exception-handling just to catch ValueErrors from `mutate` and `recombine`. However, those errors should not be thrown at all, since they didn't mean any issues but some rare, random and valid situation where the certain transformations were not executable.
Additionally, the patch fixes an uncovered issue with the usage of `random.sample`: since Python 3.11 it only accepts sequences as the first parameter without any automatic conversion. Since we passed a set previously, it needed to be casted explicitly.
> Avoid hiding issues in grammarinator-generate

- .github/workflows/main.yml
- .readthedocs.yml
- README.rst
- RELNOTES.rst
- docs/Makefile
- docs/cli.rst
- docs/conf.py
- docs/grammarinator.rst
- docs/grammarinator.runtime.rst
- docs/index.rst
- docs/introduction.rst
- docs/license.rst
- docs/make.bat
- docs/relnotes.rst
- docs/requirements.txt
- grammarinator/generate.py
- grammarinator/parse.py
- grammarinator/process.py
- grammarinator/runtime/cooldown_model.py
- grammarinator/runtime/custom_weights_model.py
- grammarinator/runtime/default_listener.py
- grammarinator/runtime/default_model.py
- grammarinator/runtime/dispatching_listener.py
- grammarinator/runtime/dispatching_model.py
- grammarinator/runtime/generator.py
- grammarinator/runtime/serializer.py
- grammarinator/runtime/tree.py
- tox.ini
Added lots of doc comment. Setup for readthedocs and for testing documentation generation with tox. Improved the visibility of some methods.
> Add API and CLI documentation

- grammarinator/generate.py
- grammarinator/tool/__init__.py
- grammarinator/tool/generator.py
Change class name to unify the tool classes.
Adjust visibility of class members.
> Refactor Generator (the tool) into GeneratorTool

- grammarinator/runtime/__init__.py
- grammarinator/runtime/listener.py
- grammarinator/runtime/model.py
- grammarinator/runtime/serializer.py
- grammarinator/runtime/tree.py
> Rename BaseRule to Rule

- README.rst
- examples/grammars/HTMLLexer.g4
- examples/grammars/HTMLParser.g4
- grammarinator/tool/processor.py
- grammarinator/tool/resources/codegen/GeneratorTemplate.py.jinja
- tests/grammars/Custom.g4
ANTLR does not support it either.
> Remove support of the `member` alias of the `members` named action

- README.rst
- setup.cfg
Also document that ANTLR requires Java 11 at least.
> Bump ANTLR dependency to 4.13.1

- .pylintrc
- examples/fuzzer/HTMLCustomGenerator.py
- tests/grammars/CustomSubclassGenerator.py
- tests/grammars/SuperGenerator.py
- tests/reparse.py
- tox.ini
- Avoid wildcard imports
- Reuse inators.imp.import_object
> Ensure test quality via linting

- grammarinator/tool/default_population.py
Removed checks based on old unlexer concepts and added some formatting to make the output more readable.
> Improve the debug print of the generated tree

- .pylintrc
- grammarinator/tool/generator.py
- Fix documentation: the method does not return a tuple anymore.
- Improve internals: no need for lambdas all the time,
> Improve GeneratorTool.create

- grammarinator/runtime/generator.py
- grammarinator/runtime/rule.py
- grammarinator/tool/generator.py
- tox.ini
Also build documentation in nit-picky mode from now on to avoid similar issues in the future.
> Documentation fixes (RuleSize.max-related)

- grammarinator/tool/processor.py
Furthermore, make _parse_grammar static, since it doesn't use anything from ProcessorTool and unify the calling of static methods.
> Make ANTLR grammar graph building functionality of ProcessorTool public

- grammarinator/tool/processor.py
Until now, `str.isnumeric()` was used to detect semantic predicates that had fixed values. However, that could only detect integers. Anything with a decimal point was rejected. Fixed to use `float()`.
> Recognize all float literals as static conditions in semantic predicates

- grammarinator/runtime/__init__.py
- grammarinator/runtime/population.py
- grammarinator/tool/__init__.py
- grammarinator/tool/default_population.py
- grammarinator/tool/generator.py
Add Individual and DefaultIndividual classes defining the API of such individuals and an actual implementation of it maintaining file-based populations. The patch doesn't change any semantics, but separates ideas.
> Move all information related to a population item into a dedicated class

- grammarinator/tool/generator.py
Add a new mutator that swaps two disjunct and compatible subtrees inside a single input test.
> Add `swap_local_nodes` mutator

- grammarinator/tool/generator.py
Add new mutator, that selects two compatible quantifiers of the same input and copies a random child of the second quantifier into the first one.
> Add `insert_local_node` mutator

- grammarinator/tool/resources/fbs/FBRule.fbs
- setup.cfg
Also fix documentation on how to generate Python code from the fbs file.
> Pin flatbuffers to 24.3.25

- grammarinator/runtime/population.py
- grammarinator/tool/default_population.py
And make existing `__bool__()` method use it.
> Add method `empty()` to the API of Population

- grammarinator/runtime/population.py
- grammarinator/tool/generator.py
Also rename some related variables in GeneratorTool.
> Rename Annotations.token_counts to node_tokens

- examples/fuzzer/HTMLCustomGenerator.py
- grammarinator/runtime/rule.py
- tests/grammars/CustomSubclassGenerator.py
- tests/grammars/SuperClass.g4
- tests/grammars/SuperClassOption.g4
- tests/grammars/SuperGenerator.py
We rely on it not being None at several places.
> Make name arg of UnlexerRule mandatory

- README.rst
Added reference of the "Grammarinator Meets LibFuzzer: A Structure-Aware In-Process Approach." paper.
> Add new citation to the README
